removing pry; causing error
2015-04-19T12:17:12.689299+00:00 heroku[bot.1]: Starting process with command `bundle exec ruboty`
2015-04-19T12:17:13.336858+00:00 heroku[bot.1]: State changed from starting to up
2015-04-19T12:17:15.987035+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:9:in `gem_installed?': undefined method `source_index' for Gem:Module (NoMethodError)
2015-04-19T12:17:15.987058+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:15:in `block in command_dependencies_met?'
2015-04-19T12:17:15.987060+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `each'
2015-04-19T12:17:15.987062+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `all?'
2015-04-19T12:17:15.987065+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base.rb:53:in `command'
2015-04-19T12:17:15.987064+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `command_dependencies_met?'
2015-04-19T12:17:15.987067+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/commands.rb:195:in `<class:Commands>'
2015-04-19T12:17:15.987068+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/commands.rb:12:in `<class:Pry>'
2015-04-19T12:17:15.987070+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry/commands.rb:9:in `<top (required)>'
2015-04-19T12:17:15.987072+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry.rb:23:in `require'
2015-04-19T12:17:15.987075+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
2015-04-19T12:17:15.987077+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2015-04-19T12:17:15.987074+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/pry-0.8.3/lib/pry.rb:23:in `<top (required)>'
2015-04-19T12:17:15.987080+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
2015-04-19T12:17:15.987078+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
2015-04-19T12:17:15.987085+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
2015-04-19T12:17:15.987081+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
2015-04-19T12:17:15.987086+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
2015-04-19T12:17:15.987087+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:63:in `bundle'
2015-04-19T12:17:15.987089+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:18:in `run'
2015-04-19T12:17:15.987090+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/ruboty-1.2.1/lib/ruboty/commands/run.rb:5:in `call'
2015-04-19T12:17:15.987100+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/ruboty-1.2.1/bin/ruboty:6:in `<top (required)>'
2015-04-19T12:17:15.987102+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/bin/ruboty:23:in `load'
2015-04-19T12:17:15.987103+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.2.0/bin/ruboty:23:in `<main>'
2015-04-19T12:17:16.559206+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=bobotonslack.herokuapp.com request_id=b915a98f-7ea4-48eb-8794-99682ee279ed fwd="54.173.169.130" dyno= connect= service= status=503 bytes=
2015-04-19T12:17:16.899065+00:00 heroku[bot.1]: State changed from up to crashed